version: '3.8'

services:
  # Backend API Only
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: nutrition-backend-only
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgresql://neondb_owner:npg_eTQRUoZ2FtG9@ep-curly-scene-a2i7a758-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key-here}
      PORT: 3001
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3001}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nutrition-backend-network 